#!/usr/bin/env python3

import time
import sys
import json

from Axon.Scheduler import scheduler

from weatherscraper.daemon import Daemon
from weatherscraper.logging import log
from weatherscraper.components import build_system

try:
    config = json.load(open("/etc/c-weatherscraper/config.json"))
except IOError:
    config = json.load(open("../etc/c-weatherscraper/config.json"))


class MyDaemon(Daemon):
    def run(self):
        log("startup")
        log(*sys.argv)
        log(config)
        interval = int(config['interval'])
        log("Running at interval of '%i' seconds." % interval)
        log("Outputting to '%s'." % config['place'])

        build_system()
        #weatherScraper(location=config['place'], interval=interval)
        scheduler.run.runThreads()


if __name__ == "__main__":
    daemon = MyDaemon('/var/run/c-weatherscraper.pid',
                      stdout='/tmp/c-weatherscraper.out',
                      stderr='/tmp/c-weatherscraper.err',
                      user='c-weatherscraper',
                      group='c-weatherscraper')

    if len(sys.argv) >= 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        else:
            print("Unknown command")
            sys.exit(2)
        sys.exit(0)
    else:
        print(sys.argv)
        print("usage: %s start|stop|restart" % sys.argv[0])
        sys.exit(2)
