#!/usr/bin/env python3

import sys
import json

from Axon.Scheduler import scheduler

from hfos.daemon import Daemon
from hfos.utils.logger import log
from hfos.system import build_system


try:
    config = json.load(open("/etc/hfos/config.json"))
except IOError:
    config = json.load(open("../etc/hfos/config.json"))


class MyDaemon(Daemon):
    def run(self):
        log("startup")
        log(*sys.argv)
        log(config)
        interval = int(config['interval'])
        log("Running at interval of '%i' seconds." % interval)
        log("Outputting to '%s'." % config['place'])

        build_system()
        #weatherScraper(location=config['place'], interval=interval)
        scheduler.run.runThreads()


if __name__ == "__main__":
    daemon = MyDaemon('/var/run/hfos.pid',
                      stdout='/tmp/hfos.out',
                      stderr='/tmp/hfos.err',
                      user='hfos',
                      group='hfos')

    if len(sys.argv) >= 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        else:
            print("Unknown command")
            sys.exit(2)
        sys.exit(0)
    else:
        print(sys.argv)
        print("usage: %s start|stop|restart" % sys.argv[0])
        sys.exit(2)
