#!/usr/bin/env python3

print("Does currently NOT work. Will probably not be restored.")
sys.exit(-1)

from weatherscraper.components import build_weatherScraper
from Axon.Scheduler import scheduler

build_weatherScraper(location="./",template="weather_c-base")

scheduler.run.runThreads()

