#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

__author__ = 'riot'
__copyright__ = "Copyright 2011-2014, Hackerfleet Community"
__license__ = "GPLv3"
__status__ = "Beta"

from Axon.Scheduler import scheduler

from hfos.system import build_system

if __name__ == '__main__':
    build_system(online=False, debug=True)

    scheduler.run.runThreads()